set(_CATKIN_CURRENT_PACKAGE "cartographer_rviz")
set(cartographer_rviz_MAINTAINER "The Cartographer Authors <google-cartographer@googlegroups.com>")
set(cartographer_rviz_DEPRECATED "")
set(cartographer_rviz_VERSION "0.2.0")
set(cartographer_rviz_BUILD_DEPENDS "g++-static" "cartographer" "cartographer_ros" "cartographer_ros_msgs" "eigen_conversions" "libqt5-core" "libqt5-gui" "libqt5-widgets" "message_runtime" "qtbase5-dev" "roscpp" "roslib" "rviz")
set(cartographer_rviz_RUN_DEPENDS "cartographer" "cartographer_ros" "cartographer_ros_msgs" "eigen_conversions" "libqt5-core" "libqt5-gui" "libqt5-widgets" "message_runtime" "qtbase5-dev" "roscpp" "roslib" "rviz")
set(cartographer_rviz_BUILDTOOL_DEPENDS "catkin")