set(_CATKIN_CURRENT_PACKAGE "cartographer_ros_msgs")
set(cartographer_ros_msgs_MAINTAINER "The Cartographer Authors <google-cartographer@googlegroups.com>")
set(cartographer_ros_msgs_DEPRECATED "")
set(cartographer_ros_msgs_VERSION "0.2.0")
set(cartographer_ros_msgs_BUILD_DEPENDS "message_generation" "geometry_msgs")
set(cartographer_ros_msgs_RUN_DEPENDS "geometry_msgs")
set(cartographer_ros_msgs_BUILDTOOL_DEPENDS "catkin")